# Generated by Django 4.2.11 on 2026-06-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_type',
            field=models.CharField(choices=[('module', 'Per Module'), ('semester', 'Per Semester'), ('term', 'Per Term')], default='module', max_length=10),
        ),
    ]
