# Generated by Django 4.2.11 on 2026-06-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_pricing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('KES', 'KES (KSh)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='USD', max_length=3),
        ),
    ]
