# Generated by Django 6.0.4 on 2026-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='country_outside_kenya',
            field=models.CharField(blank=True, help_text='Fill only if you reside outside Kenya', max_length=100),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='data_consent',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='By filling this form, you are consenting that the data being given shall be used solely for purposes of training and deployment for attachment engagement.', max_length=3, verbose_name='Data Protection Consent'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='mean_grade',
            field=models.CharField(help_text='e.g. B+ or 3.8/4.0', max_length=20, verbose_name='Mean Grade / Final Grade'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='year_of_completion',
            field=models.CharField(help_text='e.g. 2020', max_length=4),
        ),
    ]
