# Generated by Django 4.2.11 on 2026-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='base_price_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
