# Generated by Django 6.0.4 on 2026-06-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseapplication_country_outside_kenya_and_more'),
        ('courses', '0004_course_base_price_kes'),
    ]

    operations = [
    ]
